### Verbo GET – listar todos
GET http://localhost:8000/produto/ HTTP/1.1

### Verbo GET – listar um
GET http://localhost:8000/produto/10 HTTP/1.1

### Verbo POST – adicionar
POST http://127.0.0.1:8000/produto/ HTTP/1.1
content-type: application/json

{
    "nome" : "Painço da Silva",
    "cpf" : "666777888",
    "telefone" : "49966634567",
    "senha" : "peninhas",
    "matricula" : "54309",
    "grupo" : 1
}


### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/produto/2 HTTP/1.1
content-type: application/json

{
    "nome" : "Bolinhas dos Mares",
    "cpf" : "109874653213",
    "telefone" : "49898009",
    "senha" : "ariel",
    "matricula" : "88866",
    "grupo" : 2
}


### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/produto/3 HTTP/1.1